### ISSUE TITLE
Idea: Make this into a python package that can be installed with pip

### ISSUE THREAD

**Issue by einarf** [DalyaG/PyGraphicsGui#2]
Hello!

It would be nice if this package could be installed with `pip` or `pip3` and having the possibility of uploading to PyPI. There just needs to be a small adjustment in the source structure to easily support this. We need a directory containing the package content.

This can for example be:
```
PyGraphicsGui/graphics_gui
PyGraphicsGui/src/graphics_gui
```

All imports will then use `graphics_gui` as the root package.
```
from graphics_gui.window_manager import WindowManager
```

I can fix this in a pull request if you want including updating `README` with install instructions from source and the `setup.py` script that defines the package.

**Comment by DalyaG** [comment]
I did think about making it a package, but I wasn't able to find a use-case...
This project in itself is not "standalone", meaning I don't expect someone to use it as-is.
I expect users to clone and expand to make other projects of their own.

If you can think of a use-case for this project as-is, then it would be my utmost pleasure to approve a pull request from you and make it into a pip package :)

**Comment by einarf** [comment]
Ah right. I will think about this after playing around with things 😄

**Comment by einarf** [comment]
Definitly closing this. You are right that this is more of a sandbox.
